config/routes.rb
Rails.application.routes.draw do
  resources :markets, only: [:index, :show]
  resources :vendors, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  def index
    @facade = MarketFacade.new.all_markets
  end

  def show
    @facade = MarketFacade.new.market(params[:id])
    @vendors = MarketFacade.new.market_vendors(params[:id])
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  def show
    @facade = VendorFacade.new.vendor(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketMoneyFe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/markets/index.html.erb
<section id="heading">
  <h1> Markets </h1>
</section>

<section id="markets">
  <% @facade.each do |market| %>
    <div class="market">
      <h2><%= market.name %></h2>
      <p><%= market.city %>, <%= market.state %></p>
      <%= button_to "More Info", market_path(market.id), method: :get %>
    </div>
  <% end %>
</section>

app/views/markets/show.html.erb
<h1><%= @facade.name %></h1>
<p><%= @facade.street %></p><br/>
<p><%= @facade.city%>, <%= @facade.state%> <%= @facade.zip%></p><br/>


<h2>Vendors at this Location</h2>
<% @vendors.each do |vendor| %>
  <p><%= link_to "#{vendor.name}", vendor_path(vendor.id) %></p>
<% end %>

app/views/vendors/show.html.erb
<h1><%= @facade.name %></h1>

<section id="contact-info">
Contact Information:<br/>
Name: <%= @facade.contact_name %><br/>
Phone: <%= @facade.contact_phone %><br/>
Credit Accepted? <% if @facade.credit_accepted == nil %> No <% else %> Yes <% end %><br/>

Description<br/>
<%= @facade.description %>